wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.17
    framework: huggingface
    huggingface_version: 4.20.0.dev0
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: loss
      6:
      - 3
      7:
      - 1
    - 1: acc
      6:
      - 3
      7:
      - 2
    - 1: train/step
      6:
      - 3
    - 1: train/loss
      5: 3
      6:
      - 1
    python_version: 3.7.13
    start_time: 1654293610
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      3:
      - 1
      - 7
      4: 3.7.13
      5: 0.12.17
      6: 4.20.0.dev0
      8:
      - 5
